# Generated by Django 6.0.3 on 2026-03-30 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('protein', 'Proteine'), ('grain', 'Cereale & Paste'), ('vegetable', 'Legume'), ('fruit', 'Fructe'), ('dairy', 'Lactate'), ('fat', 'Grasimi & Uleiuri'), ('snack', 'Snacks'), ('drink', 'Bauturi'), ('other', 'Altele')], default='other', max_length=20)),
                ('kcal_per_100g', models.DecimalField(decimal_places=2, max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fiber_per_100g', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aliment',
                'verbose_name_plural': 'Alimente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Mic dejun'), ('lunch', 'Pranz'), ('dinner', 'Cina'), ('snack', 'Gustare')], default='lunch', max_length=15)),
                ('grams', models.DecimalField(decimal_places=1, max_digits=6)),
                ('kcal', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=7)),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6)),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6)),
                ('fat_g', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6)),
                ('fiber_g', models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=6)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intrare jurnal',
                'verbose_name_plural': 'Jurnal alimentar',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_kcal', models.DecimalField(decimal_places=1, default=0, max_digits=8)),
                ('total_protein', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_carbs', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('total_fat', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reteta',
                'verbose_name_plural': 'Retete',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.DecimalField(decimal_places=1, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.food')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='tracker.recipe')),
            ],
            options={
                'verbose_name': 'Ingredient reteta',
                'verbose_name_plural': 'Ingrediente reteta',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark-aura', 'Dark Aura'), ('fresh-mint', 'Fresh Mint'), ('warm-coral', 'Warm Coral'), ('slate-pro', 'Slate Pro')], default='dark-aura', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin'), ('O', 'Altul')], max_length=1)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentar'), ('light', 'Usor activ'), ('moderate', 'Moderat activ'), ('active', 'Activ'), ('very_active', 'Foarte activ')], default='moderate', max_length=20)),
                ('goal', models.CharField(choices=[('lose', 'Slabit'), ('maintain', 'Mentinere'), ('gain', 'Masa musculara')], default='maintain', max_length=10)),
                ('daily_kcal_target', models.PositiveIntegerField(default=2000)),
                ('protein_target_g', models.PositiveIntegerField(default=150)),
                ('carbs_target_g', models.PositiveIntegerField(default=200)),
                ('fat_target_g', models.PositiveIntegerField(default=65)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilizator',
                'verbose_name_plural': 'Profile utilizatori',
            },
        ),
        migrations.CreateModel(
            name='BodyWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Greutate corporala',
                'verbose_name_plural': 'Greutati corporale',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
