# Generated by Django 6.0.3 on 2026-03-31 16:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyweight',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
