# Generated by Django 6.0.3 on 2026-03-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_bodyweight_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyweight',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
