# Generated by Django 6.0.3 on 2026-04-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_bodyweight_notes'),
        ('tracker', '002_food_off_code'),
    ]

    operations = [
    ]
