# Generated by Django 6.0.3 on 2026-04-14 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(default='', help_text='Scrie numele ingredientului', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.food'),
        ),
    ]
