# Generated by Django 6.0.3 on 2026-04-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_recipeingredient_name_alter_recipeingredient_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
