# Generated by Django 6.0.3 on 2026-04-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_recipeingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prep_time_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
